# Generated by Django 6.0.7 on 2026-07-21 23:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        ('requests_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='itemrequest',
            constraint=models.UniqueConstraint(fields=('listing', 'requester'), name='unique_request_per_listing_and_user'),
        ),
    ]
